### ISSUE TITLE
Error “SKU must be unique” on updating entries

### ISSUE THREAD

**Issue by klick** [workingconcept/snipcart-craft-plugin#12]
**Describe the bug**

Products can not be saved. Craft throws a **“SKU must be unique”**-Error on _Update entry_ although the SKU is unique. I am using the _Snipcart Product Details_ field type.

_Edit:_
The error is **“Couldn’t publish draft.”** with the reason “SKU must be unique” given.

**To Reproduce**

1. Open existing entry.
2. Modify any custom field.
3. Click _Update entry_
4. See error.

**Expected behavior**

Entry is being updated.

**Software**

 - Craft version: 3.2.0-RC2
 - Snipcart plugin version: 1.1.1
 - PHP version: 7.2
 - Browser Chromium: 75.0.3770.100

**Additional context**

Probably a Problem with Craft’s new handling of Drafts?
---

Please don't post full logs here! Send to support@workingconcept.com.

**Comment by mattstein** [comment]
Thanks for the report, @klick! I'll take a look soon and get this worked out.

**Comment by mattstein** [comment]
While I've still got some work to do, this branch should fix the validation problem in 3.2.0-RC2: https://github.com/workingconcept/snipcart-craft-plugin/tree/1.1.2

**Comment by klick** [comment]
Thank you!

I couldn’t install this version but will instead just replace `ProductDetails.php` for the time being.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package workingconcept/craft-snipcart 1.1.2 exists as workingconcept/craft-snipcart[1.0.0, 1.0.0-beta.1, 1.0.0-beta.10, 1.0.0-beta.11, 1.0.0-beta.12, 1.0.0-beta.13, 1.0.0-beta.14, 1.0.0-beta.15, 1.0.0-beta.16, 1.0.0-beta.17, 1.0.0-beta.18, 1.0.0-beta.2, 1.0.0-beta.20, 1.0.0-beta.21, 1.0.0-beta.22, 1.0.0-beta.23, 1.0.0-beta.24, 1.0.0-beta.25, 1.0.0-beta.26, 1.0.0-beta.27, 1.0.0-beta.3, 1.0.0-beta.4, 1.0.0-beta.5, 1.0.0-beta.6, 1.0.0-beta.7, 1.0.0-beta.8, 1.0.0-beta.9, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.6.1, 1.0.7, 1.0.7.x-dev, 1.1.0, 1.1.1, 1.1.2.x-dev, dev-docs, dev-master] but these are rejected by your constraint.
```

**Comment by klick** [comment]
Just updated to the last version and that bug is back. Was that that wrong action?

**Comment by mattstein** [comment]
We're waiting on me to test and release this fix, @klick. I'm looking to have that done by the end of this week!

**Comment by klick** [comment]
Ok cool. Thanks.

**Comment by mattstein** [comment]
Finally released in [1.1.2](https://github.com/workingconcept/snipcart-craft-plugin/releases/tag/1.1.2). Sorry for the long wait, @klick!

**Comment by klick** [comment]
No problem!
